version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers-legacy
        environment:
          - BUNDLER_VERSION: 2.1.4
          - RAILS_ENV: 'test'
    executor: ruby/default
    steps:
      - run: echo 'HEllO World!'




# # https://circleci.com/docs/2.0/language-ruby/#sample-configuration
# version: 2.1
# orbs:
#   ruby: circleci/ruby@0.1.2
# jobs:
#   build:
#     docker:
#       - image: cimg/ruby:2.7.2-node-browsers-legacy
#         environment:
#           - BUNDER_VERSION: 2.1.4
#           - RAILS_ENV: 'test'
#       - image: circleci/mysql: 5.7
#         environment:
#           - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#           - MYSQL_ROOT_HOST: '%'
#           - MYSQL_USER: root
#           - MYSQL_DB: ci_test
#     working_directory: ~/repo
#     steps:
#       - checkout # CI環境上の working_directory の値の場所にGitリポジトリをコピーする。

#       # Restore bundle cache
#       - restore_cache:
#           keys:
#             - rails-demo-{{ checksum "Gemfile.lock" }}
#             - rails-demo-

#       # Bundle install dependencies
#       - run:
#           name: Install dependencies
#           command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

#       - run: sudo apt install -y postgresql-client || true

#       # Store bundle cache
#       - save_cache:
#           key: rails-demo-{{ checksum "Gemfile.lock" }}
#           paths:
#             - vendor/bundle

#       - run:
#           name: Database Setup
#           command: |
#             bundle exec rake db:create
#             bundle exec rake db:structure:load

#       - run:
#           name: Parallel RSpec
#           command: bin/rails test

#       # Save artifacts
#       - store_test_results:
#           path: /tmp/test-results

#       - run:
#           name: Rubocop
#           command: bundle exec rubocop
#       - run:
#           name: RSpec
#           command: bundle exec rspec
